#!/usr/bin/env bash

echo "#define TESTING
#include \"../src/$2.c\"

int main() {
    TESTSUITE_RUN($1);
    return 0;
}
" > test/.tmp.c

gcc -std=c99 -Wall -Werror -pedantic -o test/$1 test/.tmp.c && test/$1
rm test/.tmp.c

