#!/usr/bin/env python

import os
import glob
for filename in glob.glob('eg/*'):
    name = filename.split('/')[-1].split('.')[0]
    os.system('./fuga ' + filename)
    os.system('cp log.txt gcdata/%s.txt' % name)


